import os
import json
import uuid
from datetime import datetime, timezone

from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

# ---------------------------------------------------------------------------
# Rate limiting (will enforce limits in Milestone 5 — set up now)
# ---------------------------------------------------------------------------
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# ---------------------------------------------------------------------------
# Groq client
# ---------------------------------------------------------------------------
groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

# ---------------------------------------------------------------------------
# Audit log (JSON file — simple, structured, no extra dependencies)
# ---------------------------------------------------------------------------
LOG_FILE = "audit_log.json"


def read_log():
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        try:
            return json.load(f)
        except json.JSONDecodeError:
            return []


def write_log(entries):
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)


def append_log(entry):
    entries = read_log()
    entries.append(entry)
    write_log(entries)


# ---------------------------------------------------------------------------
# In-memory content store (maps content_id → entry for appeal lookups)
# We also persist this to a JSON file so it survives restarts.
# ---------------------------------------------------------------------------
CONTENT_FILE = "content_store.json"


def read_store():
    if not os.path.exists(CONTENT_FILE):
        return {}
    with open(CONTENT_FILE, "r") as f:
        try:
            return json.load(f)
        except json.JSONDecodeError:
            return {}


def write_store(store):
    with open(CONTENT_FILE, "w") as f:
        json.dump(store, f, indent=2)


def store_content(content_id, data):
    store = read_store()
    store[content_id] = data
    write_store(store)


def get_content(content_id):
    return read_store().get(content_id)


def update_content_status(content_id, status):
    store = read_store()
    if content_id in store:
        store[content_id]["status"] = status
        write_store(store)
        return True
    return False


# ---------------------------------------------------------------------------
# Signal 1: LLM Classifier (Groq)
# ---------------------------------------------------------------------------
LLM_PROMPT = """You are an AI content attribution classifier. Analyze the text below and assess the probability that it was generated by an AI language model (as opposed to written by a human).

Consider:
- Overly balanced or formulaic sentence structure
- Generic transitions ("furthermore", "it is important to note", "in conclusion")
- Lack of personal voice, specific anecdote, or genuine uncertainty
- Unnaturally smooth and uniform flow
- Vocabulary that is correct but feels optimized rather than chosen

Respond with ONLY a valid JSON object in this exact format (no markdown, no explanation):
{"ai_probability": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"}

Text to analyze:
"""


def classify_with_llm(text: str) -> dict:
    """
    Calls Groq LLM to assess AI probability.
    Returns {"score": float, "reasoning": str}
    Score of 1.0 = highly likely AI-generated.
    Score of 0.0 = highly likely human-written.
    """
    try:
        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "user",
                    "content": LLM_PROMPT + text
                }
            ],
            temperature=0,
            max_tokens=200,
        )
        raw = response.choices[0].message.content.strip()

        # Strip markdown fences if the model adds them anyway
        raw = raw.replace("```json", "").replace("```", "").strip()

        parsed = json.loads(raw)
        score = float(parsed.get("ai_probability", 0.5))
        score = max(0.0, min(1.0, score))  # clamp to [0, 1]
        reasoning = parsed.get("reasoning", "")
        return {"score": score, "reasoning": reasoning}

    except Exception as e:
        # Fallback: neutral score if API call fails
        print(f"[LLM signal error] {e}")
        return {"score": 0.5, "reasoning": f"LLM signal unavailable: {str(e)}"}


# ---------------------------------------------------------------------------
# Transparency label (placeholder — full version in Milestone 5)
# ---------------------------------------------------------------------------
def generate_label(confidence: float, certificate: bool = False) -> str:
    if certificate:
        return (
            "This content was created by a Verified Human creator. "
            "The creator has completed an additional verification step confirming human authorship."
        )
    if confidence >= 0.70:
        return (
            "Our system's analysis suggests this content was likely AI-generated. "
            "This label is based on automated analysis and may not be accurate. "
            "If you are the creator and believe this is wrong, you can submit an appeal."
        )
    elif confidence >= 0.40:
        return (
            "Our system could not confidently determine whether this content was written by a "
            "human or generated by AI. The analysis is inconclusive. If you are the creator, "
            "you may submit an appeal to provide additional context."
        )
    else:
        return (
            "Our system's analysis suggests this content was likely written by a human. "
            "Attribution labels help readers understand the origin of creative work."
        )


def score_to_attribution(confidence: float) -> str:
    if confidence >= 0.70:
        return "likely_ai"
    elif confidence >= 0.40:
        return "uncertain"
    else:
        return "likely_human"


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Request body must be JSON"}), 400

    text = data.get("text", "").strip()
    creator_id = data.get("creator_id", "").strip()

    if not text:
        return jsonify({"error": "Missing required field: text"}), 400
    if not creator_id:
        return jsonify({"error": "Missing required field: creator_id"}), 400

    # Short text warning
    word_count = len(text.split())
    short_text_warning = word_count < 50

    # --- Signal 1: LLM ---
    llm_result = classify_with_llm(text)
    llm_score = llm_result["score"]

    # Milestone 3: use LLM score as placeholder confidence
    # (Signals 2 & 3 added in Milestone 4)
    confidence = llm_score
    attribution = score_to_attribution(confidence)
    label = generate_label(confidence)

    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()

    # Build audit log entry
    log_entry = {
        "entry_type": "submission",
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": timestamp,
        "attribution": attribution,
        "confidence": round(confidence, 4),
        "llm_score": round(llm_score, 4),
        "stylometric_score": None,   # filled in Milestone 4
        "burstiness_score": None,    # filled in Milestone 4
        "status": "classified",
        "short_text_warning": short_text_warning,
    }
    append_log(log_entry)

    # Store for appeal lookups
    store_content(content_id, {
        "creator_id": creator_id,
        "attribution": attribution,
        "confidence": round(confidence, 4),
        "status": "classified",
        "timestamp": timestamp,
    })

    response = {
        "content_id": content_id,
        "attribution": attribution,
        "confidence": round(confidence, 4),
        "signal_scores": {
            "llm": round(llm_score, 4),
            "stylometric": None,
            "burstiness": None,
        },
        "label": label,
        "short_text_warning": short_text_warning,
    }
    return jsonify(response), 200


@app.route("/log", methods=["GET"])
def get_log():
    entries = read_log()
    # Return most recent 50 entries
    return jsonify({"entries": entries[-50:], "total": len(entries)}), 200


@app.route("/appeal", methods=["POST"])
def appeal():
    # Stub — fully implemented in Milestone 5
    return jsonify({"message": "Appeals endpoint coming in Milestone 5"}), 200


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok"}), 200


# ---------------------------------------------------------------------------
if __name__ == "__main__":
    app.run(debug=True, port=5000)
